services:
  nginx:
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
      - ./src:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - db
      - php
  php:
    image: php83fpm:latest
    build: ./
    volumes:
      - ./src:/app
    restart: always
    depends_on:
      - db
  db:
    image: mysql:lts
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: always

volumes:
  db-data:
